//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Vimas.Models.Entities.Services
{
    using System;
    using System.Collections.Generic;
    
    
    public partial interface IAspNetRolesService : SkyWeb.DatVM.Data.IBaseService<AspNetRoles>
    {
    }
    
    public partial class AspNetRolesService : SkyWeb.DatVM.Data.BaseService<AspNetRoles>, IAspNetRolesService
    {
        public AspNetRolesService(SkyWeb.DatVM.Data.IUnitOfWork unitOfWork, Repositories.IAspNetRolesRepository repository) : base(unitOfWork, repository)
        {
        }
    }
}
