//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Vimas.Models.Entities.Services
{
    using System;
    using System.Collections.Generic;
    
    
    public partial interface ICongTyChungNgheService : SkyWeb.DatVM.Data.IBaseService<CongTyChungNghe>
    {
    }
    
    public partial class CongTyChungNgheService : SkyWeb.DatVM.Data.BaseService<CongTyChungNghe>, ICongTyChungNgheService
    {
        public CongTyChungNgheService(SkyWeb.DatVM.Data.IUnitOfWork unitOfWork, Repositories.ICongTyChungNgheRepository repository) : base(unitOfWork, repository)
        {
        }
    }
}
