//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Vimas.Models.Entities.Services
{
    using System;
    using System.Collections.Generic;
    
    
    public partial interface IHopDongDOLABHocVienMappingService : SkyWeb.DatVM.Data.IBaseService<HopDongDOLABHocVienMapping>
    {
    }
    
    public partial class HopDongDOLABHocVienMappingService : SkyWeb.DatVM.Data.BaseService<HopDongDOLABHocVienMapping>, IHopDongDOLABHocVienMappingService
    {
        public HopDongDOLABHocVienMappingService(SkyWeb.DatVM.Data.IUnitOfWork unitOfWork, Repositories.IHopDongDOLABHocVienMappingRepository repository) : base(unitOfWork, repository)
        {
        }
    }
}
