//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Vimas.Models.Entities.Services
{
    using System;
    using System.Collections.Generic;
    
    
    public partial interface IHopDongDOLABService : SkyWeb.DatVM.Data.IBaseService<HopDongDOLAB>
    {
    }
    
    public partial class HopDongDOLABService : SkyWeb.DatVM.Data.BaseService<HopDongDOLAB>, IHopDongDOLABService
    {
        public HopDongDOLABService(SkyWeb.DatVM.Data.IUnitOfWork unitOfWork, Repositories.IHopDongDOLABRepository repository) : base(unitOfWork, repository)
        {
        }
    }
}
