//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Vimas.Models.Entities.Services
{
    using System;
    using System.Collections.Generic;
    
    
    public partial interface IKyTucXaHocVienMappingService : SkyWeb.DatVM.Data.IBaseService<KyTucXaHocVienMapping>
    {
    }
    
    public partial class KyTucXaHocVienMappingService : SkyWeb.DatVM.Data.BaseService<KyTucXaHocVienMapping>, IKyTucXaHocVienMappingService
    {
        public KyTucXaHocVienMappingService(SkyWeb.DatVM.Data.IUnitOfWork unitOfWork, Repositories.IKyTucXaHocVienMappingRepository repository) : base(unitOfWork, repository)
        {
        }
    }
}
