//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Vimas.Models.Entities.Services
{
    using System;
    using System.Collections.Generic;
    
    
    public partial interface INghiepDoanService : SkyWeb.DatVM.Data.IBaseService<NghiepDoan>
    {
    }
    
    public partial class NghiepDoanService : SkyWeb.DatVM.Data.BaseService<NghiepDoan>, INghiepDoanService
    {
        public NghiepDoanService(SkyWeb.DatVM.Data.IUnitOfWork unitOfWork, Repositories.INghiepDoanRepository repository) : base(unitOfWork, repository)
        {
        }
    }
}
