//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Vimas.Models.Entities.Services
{
    using System;
    using System.Collections.Generic;
    
    
    public partial interface IQuaTrinhLamViecService : SkyWeb.DatVM.Data.IBaseService<QuaTrinhLamViec>
    {
    }
    
    public partial class QuaTrinhLamViecService : SkyWeb.DatVM.Data.BaseService<QuaTrinhLamViec>, IQuaTrinhLamViecService
    {
        public QuaTrinhLamViecService(SkyWeb.DatVM.Data.IUnitOfWork unitOfWork, Repositories.IQuaTrinhLamViecRepository repository) : base(unitOfWork, repository)
        {
        }
    }
}
