//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Vimas.Models.Entities.Services
{
    using System;
    using System.Collections.Generic;
    
    
    public partial interface ISystemLogService : SkyWeb.DatVM.Data.IBaseService<SystemLog>
    {
    }
    
    public partial class SystemLogService : SkyWeb.DatVM.Data.BaseService<SystemLog>, ISystemLogService
    {
        public SystemLogService(SkyWeb.DatVM.Data.IUnitOfWork unitOfWork, Repositories.ISystemLogRepository repository) : base(unitOfWork, repository)
        {
        }
    }
}
