//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Vimas.Models.Entities.Services
{
    using System;
    using System.Collections.Generic;
    
    
    public partial interface IThongTinPhongVanService : SkyWeb.DatVM.Data.IBaseService<ThongTinPhongVan>
    {
    }
    
    public partial class ThongTinPhongVanService : SkyWeb.DatVM.Data.BaseService<ThongTinPhongVan>, IThongTinPhongVanService
    {
        public ThongTinPhongVanService(SkyWeb.DatVM.Data.IUnitOfWork unitOfWork, Repositories.IThongTinPhongVanRepository repository) : base(unitOfWork, repository)
        {
        }
    }
}
