//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Vimas.Models.Entities.Services
{
    using System;
    using System.Collections.Generic;
    
    
    public partial interface IThongTinNopTienService : SkyWeb.DatVM.Data.IBaseService<ThongTinNopTien>
    {
    }
    
    public partial class ThongTinNopTienService : SkyWeb.DatVM.Data.BaseService<ThongTinNopTien>, IThongTinNopTienService
    {
        public ThongTinNopTienService(SkyWeb.DatVM.Data.IUnitOfWork unitOfWork, Repositories.IThongTinNopTienRepository repository) : base(unitOfWork, repository)
        {
        }
    }
}
