//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Vimas.Models.Entities.Services
{
    using System;
    using System.Collections.Generic;
    
    
    public partial interface IThongTinCaNhanService : SkyWeb.DatVM.Data.IBaseService<ThongTinCaNhan>
    {
    }
    
    public partial class ThongTinCaNhanService : SkyWeb.DatVM.Data.BaseService<ThongTinCaNhan>, IThongTinCaNhanService
    {
        public ThongTinCaNhanService(SkyWeb.DatVM.Data.IUnitOfWork unitOfWork, Repositories.IThongTinCaNhanRepository repository) : base(unitOfWork, repository)
        {
        }
    }
}
