//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Vimas.Models.Entities.Services
{
    using System;
    using System.Collections.Generic;
    
    
    public partial interface IThongTinDuTuyenService : SkyWeb.DatVM.Data.IBaseService<ThongTinDuTuyen>
    {
    }
    
    public partial class ThongTinDuTuyenService : SkyWeb.DatVM.Data.BaseService<ThongTinDuTuyen>, IThongTinDuTuyenService
    {
        public ThongTinDuTuyenService(SkyWeb.DatVM.Data.IUnitOfWork unitOfWork, Repositories.IThongTinDuTuyenRepository repository) : base(unitOfWork, repository)
        {
        }
    }
}
