//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Vimas.Models.Entities.Services
{
    using System;
    using System.Collections.Generic;
    
    
    public partial interface ITrungTamGTVLService : SkyWeb.DatVM.Data.IBaseService<TrungTamGTVL>
    {
    }
    
    public partial class TrungTamGTVLService : SkyWeb.DatVM.Data.BaseService<TrungTamGTVL>, ITrungTamGTVLService
    {
        public TrungTamGTVLService(SkyWeb.DatVM.Data.IUnitOfWork unitOfWork, Repositories.ITrungTamGTVLRepository repository) : base(unitOfWork, repository)
        {
        }
    }
}
