//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Vimas.Models.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class BangCap
    {
        public int Id { get; set; }
        public int IdThongTinDuTuyen { get; set; }
        public Nullable<int> Thang { get; set; }
        public Nullable<int> Nam { get; set; }
        public string BangCap1 { get; set; }
        public Nullable<bool> DaNop { get; set; }
        public string TrinhDo { get; set; }
        public bool Active { get; set; }
    
        public virtual ThongTinDuTuyen ThongTinDuTuyen { get; set; }
    }
}
