//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Vimas.Models.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class CongTyTiepNhan
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public CongTyTiepNhan()
        {
            this.ThongTinPhongVans = new HashSet<ThongTinPhongVan>();
        }
    
        public int Id { get; set; }
        public string TenTiengAnh { get; set; }
        public string TenTiengNhat { get; set; }
        public string NganhNghe { get; set; }
        public string NguoiDaiDien { get; set; }
        public string DiaChi { get; set; }
        public string DienThoai { get; set; }
        public string Fax { get; set; }
        public Nullable<int> idNghiepDoan { get; set; }
        public bool Active { get; set; }
    
        public virtual NghiepDoan NghiepDoan { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ThongTinPhongVan> ThongTinPhongVans { get; set; }
    }
}
