//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Vimas.Models.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class HopDongDOLABHocVienMapping
    {
        public int id { get; set; }
        public Nullable<int> idThongTinCaNhan { get; set; }
        public Nullable<int> idHopDongDOLAB { get; set; }
        public Nullable<bool> isActive { get; set; }
    
        public virtual HopDongDOLAB HopDongDOLAB { get; set; }
        public virtual ThongTinCaNhan ThongTinCaNhan { get; set; }
    }
}
