//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Vimas.Models.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class QuaTrinhHocTap
    {
        public int id { get; set; }
        public int idThongTinCaNhan { get; set; }
        public Nullable<int> TuNam { get; set; }
        public Nullable<int> DenNam { get; set; }
        public string TenTruong { get; set; }
        public string LoaiTruong { get; set; }
        public string NganhHoc { get; set; }
        public Nullable<bool> DaTotNghiep { get; set; }
        public bool isActive { get; set; }
    
        public virtual ThongTinCaNhan ThongTinCaNhan { get; set; }
    }
}
