//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Vimas.Models.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class QuaTrinhLamViec
    {
        public int id { get; set; }
        public int idThongTinCaNhan { get; set; }
        public Nullable<int> TuNam { get; set; }
        public Nullable<int> DenNam { get; set; }
        public string TenCongTy { get; set; }
        public string HinhThucCongTy { get; set; }
        public string DiaChiCongTy { get; set; }
        public string ChiTietCongViec { get; set; }
        public Nullable<bool> DangLam { get; set; }
        public bool isActive { get; set; }
    
        public virtual ThongTinCaNhan ThongTinCaNhan { get; set; }
    }
}
