//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Vimas.Models.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class SucKhoe
    {
        public int Id { get; set; }
        public int IdThongTinCaNhan { get; set; }
        public string ChieuCao { get; set; }
        public string CanNang { get; set; }
        public string NhomMau { get; set; }
        public Nullable<int> TayThuan { get; set; }
        public Nullable<int> ThiLucMatTrai { get; set; }
        public Nullable<int> ThiLucMatPhai { get; set; }
        public Nullable<bool> HinhXam { get; set; }
        public Nullable<System.DateTime> NgayKhamDot1 { get; set; }
        public string GhiChuSucKhoeDot1 { get; set; }
        public Nullable<System.DateTime> NgayKhamDot2 { get; set; }
        public string GhiChuSucKhoeDot2 { get; set; }
        public bool Active { get; set; }
    
        public virtual ThongTinCaNhan ThongTinCaNhan { get; set; }
    }
}
