//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Vimas.Models.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class SystemLog
    {
        public int no { get; set; }
        public Nullable<int> id { get; set; }
        public string TenBang { get; set; }
        public string HanhDong { get; set; }
        public string ThucHienBoi { get; set; }
        public Nullable<System.DateTime> NgayThucHien { get; set; }
    }
}
