//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Vimas.Models.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class ThongTinPhongVan
    {
        public int id { get; set; }
        public int idThongTinCaNhan { get; set; }
        public Nullable<System.DateTime> NgayPhongVan { get; set; }
        public string NghePhongVan { get; set; }
        public string GhiChuPV { get; set; }
        public Nullable<System.DateTime> NgayTrungTuyen { get; set; }
        public string DotTrungTuyen { get; set; }
        public string NgheTrungTuyenTiengAnh { get; set; }
        public string NgheTrungTuyenTiengViet { get; set; }
        public Nullable<int> NghiepDoan { get; set; }
        public Nullable<int> CongTyTiepNhan { get; set; }
        public Nullable<int> ThoiHanHopDong { get; set; }
        public string GhiChuSauTrungTuyen { get; set; }
        public string LopHoc { get; set; }
        public Nullable<System.DateTime> NgayNhapHoc { get; set; }
        public Nullable<System.DateTime> NgayKetThucKhoaHoc { get; set; }
        public string GhiChuKhenThuongKyLuat { get; set; }
        public Nullable<int> CongTyChungNghe { get; set; }
        public string SoPhieuTiepNhan { get; set; }
        public string GhiChuPhaiCu { get; set; }
        public Nullable<int> HopDongTTS { get; set; }
        public Nullable<System.DateTime> NgayKyHopDong { get; set; }
        public string HinhAnh { get; set; }
        public Nullable<System.DateTime> NgayHuySauKhiTrungTuyen { get; set; }
        public string LyDoHuy { get; set; }
        public Nullable<bool> isActive { get; set; }
    
        public virtual CongTyChungNghe CongTyChungNghe1 { get; set; }
        public virtual CongTyTiepNhan CongTyTiepNhan1 { get; set; }
        public virtual ThongTinCaNhan ThongTinCaNhan { get; set; }
    }
}
