//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Vimas.Models.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class ThongTinNopTien
    {
        public int id { get; set; }
        public int idThongTinCaNhan { get; set; }
        public string LoaiTien { get; set; }
        public string SoPhieu { get; set; }
        public System.DateTime NgayLapPhieu { get; set; }
        public int ThuHayChi { get; set; }
        public decimal SoTien { get; set; }
        public string LyDo { get; set; }
        public bool isActive { get; set; }
    
        public virtual ThongTinCaNhan ThongTinCaNhan { get; set; }
    }
}
