//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Vimas.Models.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class ThongTinCaNhan
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ThongTinCaNhan()
        {
            this.HopDongDOLABHocVienMappings = new HashSet<HopDongDOLABHocVienMapping>();
            this.KyTucXas = new HashSet<KyTucXa>();
            this.QuaTrinhHocTaps = new HashSet<QuaTrinhHocTap>();
            this.QuaTrinhLamViecs = new HashSet<QuaTrinhLamViec>();
            this.SucKhoes = new HashSet<SucKhoe>();
            this.ThongTinDuTuyens = new HashSet<ThongTinDuTuyen>();
            this.ThongTinGiaDinhs = new HashSet<ThongTinGiaDinh>();
            this.ThongTinNopTiens = new HashSet<ThongTinNopTien>();
            this.ThongTinPhongVans = new HashSet<ThongTinPhongVan>();
            this.ThongTinVeNuocs = new HashSet<ThongTinVeNuoc>();
        }
    
        public int Id { get; set; }
        public string MaLuuHoSo { get; set; }
        public int IdTrungTamGTVL { get; set; }
        public string HoTen { get; set; }
        public string TenPhienAmNhat { get; set; }
        public int GioiTinh { get; set; }
        public System.DateTime NgaySinh { get; set; }
        public string NoiSinh { get; set; }
        public Nullable<int> TrinhDoVanHoa { get; set; }
        public int TinhTrangGiaDinh { get; set; }
        public string CMND { get; set; }
        public System.DateTime NgayCap { get; set; }
        public string NoiCap { get; set; }
        public string SoHoChieu { get; set; }
        public Nullable<System.DateTime> NgayCapHC { get; set; }
        public string NoiCapHC { get; set; }
        public Nullable<System.DateTime> NgayHetHan { get; set; }
        public string SoNha { get; set; }
        public string PhuongXa { get; set; }
        public string QuanHuyen { get; set; }
        public string Tinh { get; set; }
        public string DiaChiTiengAnh { get; set; }
        public string DiaChiLienLac { get; set; }
        public string DienThoaiDiDong { get; set; }
        public string DienThoaiNha { get; set; }
        public Nullable<int> CoGiay { get; set; }
        public string SizeQuanAo { get; set; }
        public bool Active { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<HopDongDOLABHocVienMapping> HopDongDOLABHocVienMappings { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<KyTucXa> KyTucXas { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<QuaTrinhHocTap> QuaTrinhHocTaps { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<QuaTrinhLamViec> QuaTrinhLamViecs { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SucKhoe> SucKhoes { get; set; }
        public virtual TrungTamGTVL TrungTamGTVL { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ThongTinDuTuyen> ThongTinDuTuyens { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ThongTinGiaDinh> ThongTinGiaDinhs { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ThongTinNopTien> ThongTinNopTiens { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ThongTinPhongVan> ThongTinPhongVans { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ThongTinVeNuoc> ThongTinVeNuocs { get; set; }
    }
}
