//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Vimas.Models.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class ThongTinCaNhan
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ThongTinCaNhan()
        {
            this.BienBan = new HashSet<BienBan>();
            this.HopDongDOLABHocVienMapping = new HashSet<HopDongDOLABHocVienMapping>();
            this.KyTucXa = new HashSet<KyTucXa>();
            this.QuaTrinhHocTap = new HashSet<QuaTrinhHocTap>();
            this.QuaTrinhLamViec = new HashSet<QuaTrinhLamViec>();
            this.SucKhoe = new HashSet<SucKhoe>();
            this.ThongTinDuTuyen = new HashSet<ThongTinDuTuyen>();
            this.ThongTinGiaDinh = new HashSet<ThongTinGiaDinh>();
            this.ThongTinNopTien = new HashSet<ThongTinNopTien>();
            this.ThongTinPhongVan = new HashSet<ThongTinPhongVan>();
            this.ThongTinVeNuoc = new HashSet<ThongTinVeNuoc>();
        }
    
        public int Id { get; set; }
        public string MaLuuHoSo { get; set; }
        public int IdTrungTamGTVL { get; set; }
        public string HoTen { get; set; }
        public string TenPhienAmNhat { get; set; }
        public int GioiTinh { get; set; }
        public System.DateTime NgaySinh { get; set; }
        public string NoiSinh { get; set; }
        public Nullable<int> TrinhDoVanHoa { get; set; }
        public int TinhTrangGiaDinh { get; set; }
        public string CMND { get; set; }
        public System.DateTime NgayCap { get; set; }
        public string NoiCap { get; set; }
        public string SoHoChieu { get; set; }
        public Nullable<System.DateTime> NgayCapHC { get; set; }
        public string NoiCapHC { get; set; }
        public Nullable<System.DateTime> NgayHetHan { get; set; }
        public string HoKhau { get; set; }
        public string DiaChiLienLac { get; set; }
        public string DiaChiTiengAnh { get; set; }
        public string DienThoaiDiDong { get; set; }
        public string DienThoaiNha { get; set; }
        public Nullable<int> CoGiay { get; set; }
        public string SizeQuanAo { get; set; }
        public bool Active { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<BienBan> BienBan { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<HopDongDOLABHocVienMapping> HopDongDOLABHocVienMapping { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<KyTucXa> KyTucXa { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<QuaTrinhHocTap> QuaTrinhHocTap { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<QuaTrinhLamViec> QuaTrinhLamViec { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SucKhoe> SucKhoe { get; set; }
        public virtual TrungTamGTVL TrungTamGTVL { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ThongTinDuTuyen> ThongTinDuTuyen { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ThongTinGiaDinh> ThongTinGiaDinh { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ThongTinNopTien> ThongTinNopTien { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ThongTinPhongVan> ThongTinPhongVan { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ThongTinVeNuoc> ThongTinVeNuoc { get; set; }
    }
}
