//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Vimas.Models.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class ThongTinGiaDinh
    {
        public int id { get; set; }
        public int idThongTinCaNhan { get; set; }
        public string HoTen { get; set; }
        public string QuanHe { get; set; }
        public System.DateTime NgaySinh { get; set; }
        public string NgheNghiep { get; set; }
        public string NoiLamViec { get; set; }
        public string DiaChi { get; set; }
        public string SoDienThoai { get; set; }
        public bool isActive { get; set; }
    
        public virtual ThongTinCaNhan ThongTinCaNhan { get; set; }
    }
}
