//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Vimas.Models.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class ThongTinDuTuyen
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ThongTinDuTuyen()
        {
            this.BangCaps = new HashSet<BangCap>();
        }
    
        public int Id { get; set; }
        public int IdThongTinCaNhan { get; set; }
        public System.DateTime NgayDangKy { get; set; }
        public string UuDiem { get; set; }
        public string NhuocDiem { get; set; }
        public string KyNangKhac { get; set; }
        public string SoThich { get; set; }
        public string LyDoDiNhat { get; set; }
        public string VeNuocLamGi { get; set; }
        public string NguoiGioiThieu { get; set; }
        public string BanBeBenNhat { get; set; }
        public string AnhChiBenNhat { get; set; }
        public Nullable<int> AnhChiDangKyOVimas { get; set; }
        public bool DaDKDiNhatOCongtyKhac { get; set; }
        public bool DaDiNuocNgoai { get; set; }
        public bool DaDiNhat { get; set; }
        public string GhiChuSoVan { get; set; }
        public bool Active { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<BangCap> BangCaps { get; set; }
        public virtual ThongTinCaNhan ThongTinCaNhan { get; set; }
    }
}
