//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Vimas.Models.Entities
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class VimasEntities : DbContext
    {
        public VimasEntities()
            : base("name=VimasEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<C__MigrationHistory> C__MigrationHistory { get; set; }
        public virtual DbSet<AspNetRoles> AspNetRoles { get; set; }
        public virtual DbSet<AspNetUserClaims> AspNetUserClaims { get; set; }
        public virtual DbSet<AspNetUserLogins> AspNetUserLogins { get; set; }
        public virtual DbSet<AspNetUsers> AspNetUsers { get; set; }
        public virtual DbSet<BangCap> BangCap { get; set; }
        public virtual DbSet<BienBan> BienBan { get; set; }
        public virtual DbSet<CongTyChungNghe> CongTyChungNghe { get; set; }
        public virtual DbSet<CongTyTiepNhan> CongTyTiepNhan { get; set; }
        public virtual DbSet<HopDongDOLAB> HopDongDOLAB { get; set; }
        public virtual DbSet<HopDongDOLABHocVienMapping> HopDongDOLABHocVienMapping { get; set; }
        public virtual DbSet<KyTucXa> KyTucXa { get; set; }
        public virtual DbSet<NghiepDoan> NghiepDoan { get; set; }
        public virtual DbSet<QuaTrinhHocTap> QuaTrinhHocTap { get; set; }
        public virtual DbSet<QuaTrinhLamViec> QuaTrinhLamViec { get; set; }
        public virtual DbSet<SucKhoe> SucKhoe { get; set; }
        public virtual DbSet<SystemLog> SystemLog { get; set; }
        public virtual DbSet<ThongTinCaNhan> ThongTinCaNhan { get; set; }
        public virtual DbSet<ThongTinDuTuyen> ThongTinDuTuyen { get; set; }
        public virtual DbSet<ThongTinGiaDinh> ThongTinGiaDinh { get; set; }
        public virtual DbSet<ThongTinNopTien> ThongTinNopTien { get; set; }
        public virtual DbSet<ThongTinPhongVan> ThongTinPhongVan { get; set; }
        public virtual DbSet<ThongTinVeNuoc> ThongTinVeNuoc { get; set; }
        public virtual DbSet<TrungTamGTVL> TrungTamGTVL { get; set; }
    }
}
