//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Vimas.Models.Entities.Repositories
{
    using System;
    using System.Collections.Generic;
    
    
    public partial interface IThongTinVeNuocRepository : SkyWeb.DatVM.Data.IBaseRepository<ThongTinVeNuoc>
    {
    }
    
    public partial class ThongTinVeNuocRepository : SkyWeb.DatVM.Data.BaseRepository<ThongTinVeNuoc>, IThongTinVeNuocRepository
    {
    	public ThongTinVeNuocRepository(System.Data.Entity.DbContext dbContext) : base(dbContext)
        {
        }
    }
}
