//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Vimas.ViewModels
{
    using System;
    using System.Collections.Generic;
    
    public partial class AspNetUserLoginsViewModel : SkyWeb.DatVM.Mvc.BaseEntityViewModel<Vimas.Models.Entities.AspNetUserLogins>
    {
    	
    			public virtual string LoginProvider { get; set; }
    			public virtual string ProviderKey { get; set; }
    			public virtual string UserId { get; set; }
    	
    	public AspNetUserLoginsViewModel() : base() { }
    	public AspNetUserLoginsViewModel(Vimas.Models.Entities.AspNetUserLogins entity) : base(entity) { }
    
    }
}
