//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Vimas.ViewModels
{
    using System;
    using System.Collections.Generic;
    
    public partial class BangCapViewModel : SkyWeb.DatVM.Mvc.BaseEntityViewModel<Vimas.Models.Entities.BangCap>
    {
    	
    			public virtual int Id { get; set; }
    			public virtual int IdThongTinDuTuyen { get; set; }
    			public virtual Nullable<int> Thang { get; set; }
    			public virtual Nullable<int> Nam { get; set; }
    			public virtual string BangCap1 { get; set; }
    			public virtual Nullable<bool> DaNop { get; set; }
    			public virtual string TrinhDo { get; set; }
    			public virtual Nullable<bool> Active { get; set; }
    	
    	public BangCapViewModel() : base() { }
    	public BangCapViewModel(Vimas.Models.Entities.BangCap entity) : base(entity) { }
    
    }
}
