//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Vimas.ViewModels
{
    using System;
    using System.Collections.Generic;
    
    public partial class CongTyChungNgheViewModel : SkyWeb.DatVM.Mvc.BaseEntityViewModel<Vimas.Models.Entities.CongTyChungNghe>
    {
    	
    			public virtual int Id { get; set; }
    			public virtual string TenVietTat { get; set; }
    			public virtual string TenTiengAnh { get; set; }
    			public virtual string TenTiengViet { get; set; }
    			public virtual string DiaChiTiengAnh { get; set; }
    			public virtual string DiaChiTiengViet { get; set; }
    			public virtual string DienThoai { get; set; }
    			public virtual string NguoiDaiDien { get; set; }
    			public virtual string ChucDanh { get; set; }
    			public virtual Nullable<decimal> VonDieuLe { get; set; }
    			public virtual Nullable<int> SoNhanVien { get; set; }
    			public virtual Nullable<bool> Active { get; set; }
    	
    	public CongTyChungNgheViewModel() : base() { }
    	public CongTyChungNgheViewModel(Vimas.Models.Entities.CongTyChungNghe entity) : base(entity) { }
    
    }
}
