//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Vimas.ViewModels
{
    using System;
    using System.Collections.Generic;
    
    public partial class HopDongDOLABHocVienMappingViewModel : SkyWeb.DatVM.Mvc.BaseEntityViewModel<Vimas.Models.Entities.HopDongDOLABHocVienMapping>
    {
    	
    			public virtual int Id { get; set; }
    			public virtual Nullable<int> IdThongTinCaNhan { get; set; }
    			public virtual Nullable<int> IdHopDongDOLAB { get; set; }
    			public virtual bool Active { get; set; }
    	
    	public HopDongDOLABHocVienMappingViewModel() : base() { }
    	public HopDongDOLABHocVienMappingViewModel(Vimas.Models.Entities.HopDongDOLABHocVienMapping entity) : base(entity) { }
    
    }
}
