//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Vimas.ViewModels
{
    using System;
    using System.Collections.Generic;
    
    public partial class HopDongDOLABViewModel : SkyWeb.DatVM.Mvc.BaseEntityViewModel<Vimas.Models.Entities.HopDongDOLAB>
    {
    	
    			public virtual int Id { get; set; }
    			public virtual Nullable<System.DateTime> NgayDangKy { get; set; }
    			public virtual Nullable<System.DateTime> NgayNhan { get; set; }
    			public virtual string SoDKHopDong { get; set; }
    			public virtual string SoCongVan { get; set; }
    			public virtual string SoPhieuTiepNhan { get; set; }
    			public virtual bool Active { get; set; }
    	
    	public HopDongDOLABViewModel() : base() { }
    	public HopDongDOLABViewModel(Vimas.Models.Entities.HopDongDOLAB entity) : base(entity) { }
    
    }
}
