//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Vimas.ViewModels
{
    using System;
    using System.Collections.Generic;
    
    public partial class KyTucXaHocVienMappingViewModel : SkyWeb.DatVM.Mvc.BaseEntityViewModel<Vimas.Models.Entities.KyTucXaHocVienMapping>
    {
    	
    			public virtual int id { get; set; }
    			public virtual Nullable<int> idThongTinCaNhan { get; set; }
    			public virtual string idKyTucXa { get; set; }
    			public virtual string Active { get; set; }
    	
    	public KyTucXaHocVienMappingViewModel() : base() { }
    	public KyTucXaHocVienMappingViewModel(Vimas.Models.Entities.KyTucXaHocVienMapping entity) : base(entity) { }
    
    }
}
