//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Vimas.ViewModels
{
    using System;
    using System.Collections.Generic;
    
    public partial class KyTucXaViewModel : SkyWeb.DatVM.Mvc.BaseEntityViewModel<Vimas.Models.Entities.KyTucXa>
    {
    	
    			public virtual int Id { get; set; }
    			public virtual Nullable<int> IdThongTinCaNhan { get; set; }
    			public virtual Nullable<System.DateTime> NgayVao { get; set; }
    			public virtual Nullable<System.DateTime> NgayRa { get; set; }
    			public virtual Nullable<int> SoPhong { get; set; }
    			public virtual Nullable<int> SoHocTuDo { get; set; }
    			public virtual string GhiChu { get; set; }
    			public virtual bool Active { get; set; }
    	
    	public KyTucXaViewModel() : base() { }
    	public KyTucXaViewModel(Vimas.Models.Entities.KyTucXa entity) : base(entity) { }
    
    }
}
