//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Vimas.ViewModels
{
    using System;
    using System.Collections.Generic;
    
    public partial class NghiepDoanViewModel : SkyWeb.DatVM.Mvc.BaseEntityViewModel<Vimas.Models.Entities.NghiepDoan>
    {
    	
    			public virtual int Id { get; set; }
    			public virtual string MaNghiepDoan { get; set; }
    			public virtual string TenNghiepDoan { get; set; }
    			public virtual string TenVietTat { get; set; }
    			public virtual string NguoiDaiDien { get; set; }
    			public virtual string ChucDanh { get; set; }
    			public virtual string DiaChi { get; set; }
    			public virtual string DienThoai { get; set; }
    			public virtual string Fax { get; set; }
    			public virtual Nullable<System.DateTime> NgayKyHopDong { get; set; }
    			public virtual Nullable<decimal> LuongCoBan { get; set; }
    			public virtual Nullable<decimal> PhiDichVu { get; set; }
    			public virtual Nullable<decimal> PhiUTDT { get; set; }
    			public virtual string WebsiteUrl { get; set; }
    			public virtual bool Active { get; set; }
    	
    	public NghiepDoanViewModel() : base() { }
    	public NghiepDoanViewModel(Vimas.Models.Entities.NghiepDoan entity) : base(entity) { }
    
    }
}
