//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Vimas.ViewModels
{
    using System;
    using System.Collections.Generic;
    
    public partial class QuaTrinhLamViecViewModel : SkyWeb.DatVM.Mvc.BaseEntityViewModel<Vimas.Models.Entities.QuaTrinhLamViec>
    {
    	
    			public virtual int Id { get; set; }
    			public virtual int IdThongTinCaNhan { get; set; }
    			public virtual Nullable<int> TuNam { get; set; }
    			public virtual Nullable<int> DenNam { get; set; }
    			public virtual string TenCongTy { get; set; }
    			public virtual string HinhThucCongTy { get; set; }
    			public virtual string DiaChiCongTy { get; set; }
    			public virtual string ChiTietCongViec { get; set; }
    			public virtual Nullable<bool> DangLam { get; set; }
    			public virtual bool Active { get; set; }
    	
    	public QuaTrinhLamViecViewModel() : base() { }
    	public QuaTrinhLamViecViewModel(Vimas.Models.Entities.QuaTrinhLamViec entity) : base(entity) { }
    
    }
}
