//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Vimas.ViewModels
{
    using System;
    using System.Collections.Generic;
    
    public partial class QuaTrinhHocTapViewModel : SkyWeb.DatVM.Mvc.BaseEntityViewModel<Vimas.Models.Entities.QuaTrinhHocTap>
    {
    	
    			public virtual int Id { get; set; }
    			public virtual int idThongTinCaNhan { get; set; }
    			public virtual Nullable<int> TuNam { get; set; }
    			public virtual Nullable<int> DenNam { get; set; }
    			public virtual string TenTruong { get; set; }
    			public virtual string LoaiTruong { get; set; }
    			public virtual string NganhHoc { get; set; }
    			public virtual Nullable<bool> DaTotNghiep { get; set; }
    			public virtual bool Active { get; set; }
    	
    	public QuaTrinhHocTapViewModel() : base() { }
    	public QuaTrinhHocTapViewModel(Vimas.Models.Entities.QuaTrinhHocTap entity) : base(entity) { }
    
    }
}
