//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Vimas.ViewModels
{
    using System;
    using System.Collections.Generic;
    
    public partial class SucKhoeViewModel : SkyWeb.DatVM.Mvc.BaseEntityViewModel<Vimas.Models.Entities.SucKhoe>
    {
    	
    			public virtual int id { get; set; }
    			public virtual int idThongTinCaNhan { get; set; }
    			public virtual string ChieuCao { get; set; }
    			public virtual string CanNang { get; set; }
    			public virtual string NhomMau { get; set; }
    			public virtual Nullable<int> TayThuan { get; set; }
    			public virtual Nullable<int> ThiLucMatTrai { get; set; }
    			public virtual Nullable<int> ThiLucMatPhai { get; set; }
    			public virtual Nullable<bool> HinhXam { get; set; }
    			public virtual Nullable<System.DateTime> NgayKhamDot1 { get; set; }
    			public virtual string GhiChuSucKhoeDot1 { get; set; }
    			public virtual Nullable<System.DateTime> NgayKhamDot2 { get; set; }
    			public virtual string GhiChuSucKhoeDot2 { get; set; }
    			public virtual bool isActive { get; set; }
    	
    	public SucKhoeViewModel() : base() { }
    	public SucKhoeViewModel(Vimas.Models.Entities.SucKhoe entity) : base(entity) { }
    
    }
}
