//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Vimas.ViewModels
{
    using System;
    using System.Collections.Generic;
    
    public partial class ThongTinPhongVanViewModel : SkyWeb.DatVM.Mvc.BaseEntityViewModel<Vimas.Models.Entities.ThongTinPhongVan>
    {
    	
    			public virtual int Id { get; set; }
    			public virtual int IdThongTinCaNhan { get; set; }
    			public virtual Nullable<System.DateTime> NgayPhongVan { get; set; }
    			public virtual string NghePhongVan { get; set; }
    			public virtual string GhiChuPV { get; set; }
    			public virtual Nullable<System.DateTime> NgayTrungTuyen { get; set; }
    			public virtual string DotTrungTuyen { get; set; }
    			public virtual string NgheTrungTuyenTiengAnh { get; set; }
    			public virtual string NgheTrungTuyenTiengViet { get; set; }
    			public virtual Nullable<int> NghiepDoan { get; set; }
    			public virtual Nullable<int> CongTyTiepNhan { get; set; }
    			public virtual Nullable<int> ThoiHanHopDong { get; set; }
    			public virtual string GhiChuSauTrungTuyen { get; set; }
    			public virtual string LopHoc { get; set; }
    			public virtual Nullable<System.DateTime> NgayNhapHoc { get; set; }
    			public virtual Nullable<System.DateTime> NgayKetThucKhoaHoc { get; set; }
    			public virtual string GhiChuKhenThuongKyLuat { get; set; }
    			public virtual Nullable<int> CongTyChungNghe { get; set; }
    			public virtual string SoPhieuTiepNhan { get; set; }
    			public virtual string GhiChuPhaiCu { get; set; }
    			public virtual Nullable<int> HopDongTTS { get; set; }
    			public virtual Nullable<System.DateTime> NgayKyHopDong { get; set; }
    			public virtual string HinhAnh { get; set; }
    			public virtual Nullable<System.DateTime> NgayHuySauKhiTrungTuyen { get; set; }
    			public virtual string LyDoHuy { get; set; }
    			public virtual bool Active { get; set; }
    	
    	public ThongTinPhongVanViewModel() : base() { }
    	public ThongTinPhongVanViewModel(Vimas.Models.Entities.ThongTinPhongVan entity) : base(entity) { }
    
    }
}
