//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Vimas.ViewModels
{
    using System;
    using System.Collections.Generic;
    
    public partial class ThongTinGiaDinhViewModel : SkyWeb.DatVM.Mvc.BaseEntityViewModel<Vimas.Models.Entities.ThongTinGiaDinh>
    {
    	
    			public virtual int Id { get; set; }
    			public virtual int IdThongTinCaNhan { get; set; }
    			public virtual string HoTen { get; set; }
    			public virtual Nullable<int> QuanHe { get; set; }
    			public virtual System.DateTime NgaySinh { get; set; }
    			public virtual string NgheNghiep { get; set; }
    			public virtual string NoiLamViec { get; set; }
    			public virtual string DiaChi { get; set; }
    			public virtual string SoDienThoai { get; set; }
    			public virtual bool Active { get; set; }
    	
    	public ThongTinGiaDinhViewModel() : base() { }
    	public ThongTinGiaDinhViewModel(Vimas.Models.Entities.ThongTinGiaDinh entity) : base(entity) { }
    
    }
}
