//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Vimas.ViewModels
{
    using System;
    using System.Collections.Generic;
    
    public partial class ThongTinVeNuocViewModel : SkyWeb.DatVM.Mvc.BaseEntityViewModel<Vimas.Models.Entities.ThongTinVeNuoc>
    {
    	
    			public virtual int id { get; set; }
    			public virtual int idThongTinCaNhan { get; set; }
    			public virtual Nullable<System.DateTime> NgayDi { get; set; }
    			public virtual Nullable<System.DateTime> NgayVe { get; set; }
    			public virtual string LyDoVe { get; set; }
    			public virtual Nullable<bool> ThanhLyHopDong { get; set; }
    			public virtual Nullable<System.DateTime> NgayThanhLy { get; set; }
    			public virtual string SoHopDongThanhLy { get; set; }
    			public virtual Nullable<System.DateTime> NgayTron { get; set; }
    			public virtual Nullable<System.DateTime> NgayBiTrucXuat { get; set; }
    			public virtual string GhiChuTheoDoi { get; set; }
    	
    	public ThongTinVeNuocViewModel() : base() { }
    	public ThongTinVeNuocViewModel(Vimas.Models.Entities.ThongTinVeNuoc entity) : base(entity) { }
    
    }
}
