//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Vimas.ViewModels
{
    using System;
    using System.Collections.Generic;
    
    public partial class ThongTinCaNhanViewModel : SkyWeb.DatVM.Mvc.BaseEntityViewModel<Vimas.Models.Entities.ThongTinCaNhan>
    {
    	
    			public virtual int Id { get; set; }
    			public virtual string MaLuuHoSo { get; set; }
    			public virtual int IdTrungTamGTVL { get; set; }
    			public virtual string HoTen { get; set; }
    			public virtual string TenPhienAmNhat { get; set; }
    			public virtual int GioiTinh { get; set; }
    			public virtual System.DateTime NgaySinh { get; set; }
    			public virtual string NoiSinh { get; set; }
    			public virtual string TrinhDoVanHoa { get; set; }
    			public virtual int TinhTrangGiaDinh { get; set; }
    			public virtual string CMND { get; set; }
    			public virtual System.DateTime NgayCap { get; set; }
    			public virtual string NoiCap { get; set; }
    			public virtual string SoHoChieu { get; set; }
    			public virtual Nullable<System.DateTime> NgayCapHC { get; set; }
    			public virtual string NoiCapHC { get; set; }
    			public virtual Nullable<System.DateTime> NgayHetHan { get; set; }
    			public virtual string SoNha { get; set; }
    			public virtual string PhuongXa { get; set; }
    			public virtual string QuanHuyen { get; set; }
    			public virtual string Tinh { get; set; }
    			public virtual string DiaChiTiengAnh { get; set; }
    			public virtual string DiaChiLienLac { get; set; }
    			public virtual string DienThoaiDiDong { get; set; }
    			public virtual string DienThoaiNha { get; set; }
    			public virtual Nullable<int> CoGiay { get; set; }
    			public virtual string SizeQuanAo { get; set; }
    			public virtual bool Active { get; set; }
    	
    	public ThongTinCaNhanViewModel() : base() { }
    	public ThongTinCaNhanViewModel(Vimas.Models.Entities.ThongTinCaNhan entity) : base(entity) { }
    
    }
}
