//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Vimas.ViewModels
{
    using System;
    using System.Collections.Generic;
    
    public partial class TrungTamGTVLViewModel : SkyWeb.DatVM.Mvc.BaseEntityViewModel<Vimas.Models.Entities.TrungTamGTVL>
    {
    	
    			public virtual int Id { get; set; }
    			public virtual string MaNguon { get; set; }
    			public virtual string TenCoSo { get; set; }
    			public virtual string DiaChi { get; set; }
    			public virtual string DienThoai { get; set; }
    			public virtual string Fax { get; set; }
    			public virtual string SoHDLK { get; set; }
    			public virtual Nullable<System.DateTime> NgayKyHopDong { get; set; }
    			public virtual Nullable<System.DateTime> NgayHetHan { get; set; }
    			public virtual string NguoiDaiDien { get; set; }
    			public virtual string ChucDanh { get; set; }
    			public virtual Nullable<bool> Active { get; set; }
    	
    	public TrungTamGTVLViewModel() : base() { }
    	public TrungTamGTVLViewModel(Vimas.Models.Entities.TrungTamGTVL entity) : base(entity) { }
    
    }
}
